scrape_configs:
  - job_name: 'Heymart Auth Metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['https://heymart-auth-staging-qwmmsp4gka-et.a.run.app']
        labels:
          application: 'heymart-auth'