name: Continuous Deployment (CD)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          export_environment_variables: true
          create_credentials_file: true
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build prometheus
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/heymart-monitoring-prometheus prometheus

      - name: Push prometheus
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/heymart-monitoring-prometheus

      - name: Deploy prometheus service
        id: 'deploy-prometheus'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'heymart-monitoring-prometheus'
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/heymart-monitoring-prometheus
          region: asia-southeast2
          timeout: 15m
      
      - name: Build grafana
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/heymart-monitoring-grafana grafana

      - name: Push grafana
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/heymart-monitoring-grafana

      - name: Deploy grafana service
        id: 'deploy-grafana'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'heymart-monitoring-grafana'
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/heymart-monitoring-grafana
          region: asia-southeast2
          timeout: 15m